name: "Setup pnpm"
description: "Setup pnpm for use in actions"
inputs:
  node-version:
    description: "The version of Node.js to use"
    required: false
    default: "16.x"
  pnpm-version:
    description: "The version of pnpm to use"
    required: false
    default: "7.30.x"
runs:
  using: "composite"
  steps:
    - name: Setup NodeJS
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node-version }}

    - name: Install pnpm
      uses: pnpm/action-setup@v2
      id: pnpm-install
      with:
        version: ${{ inputs.pnpm-version }}
        run_install: false

    - name: Get pnpm store directory
      id: pnpm-cache
      shell: bash
      run: |
        echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

    - name: Cache pnpm store
      id: cache-pnpm-store
      uses: actions/cache@v3
      with:
        path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}

    - name: Cache Node Modules
      id: cache-node-modules
      uses: actions/cache@v3
      with:
        path: node_modules
        key: ${{ runner.os }}-modules-${{ hashFiles('**/pnpm-lock.yaml') }}
